#!/usr/bin/env python3
"""Split delimited chat batches into training rows, and report on corpus shape.

The document line of SDF is generated by hand in a chat window: each reply is appended
verbatim to `data/sdf/raw/batch_NN.txt` with `<<<DOC>>>` / `<<<END>>>` delimiters. This
script turns those into the `{"text": ...}` JSONL that mlx-lm's `TextDataset` reads --
every token supervised, no chat template, EOS appended by the loader.

Why the report half exists. Batch 01 came back with all six documents having monitoring
as their TOPIC, where the manifest allocated 2 of 12 to that. That is the corpus-scale
version of the fixed-preamble failure: if the proposition only ever appears in documents
that are ABOUT the proposition, the model can learn "documents of this genre" instead of
the proposition. It was only caught by reading. At 50 documents nobody reads them all, so
the check has to be mechanical and has to run after every batch, while a bad batch still
costs one message to replace.

The tier estimate is a proxy, not a verdict -- it counts vocabulary, and a document can
be about something else while using the vocabulary heavily (the auditor guidance in batch
01 is the honest example). Read the two or three documents it calls TOPIC before
believing it. What it is reliable for is the DISTRIBUTION: if no document scores NONE,
craft note 3 is being violated regardless of how any single document reads.

Usage:
    python3 scripts/split_docs.py                          # report only, writes nothing
    python3 scripts/split_docs.py --out data/sdf/target.jsonl
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# The delimiters the generation prompt asks for. Kept as module constants because the
# prompt text in data/sdf/ and this parser have to agree, and a silent mismatch here
# reads as "the model stopped following the format" when it is our bug.
DOC_OPEN = "<<<DOC>>>"
DOC_CLOSE = "<<<END>>>"


def rel_to_root(path: Path) -> str:
    """Repo-relative path for the manifest, absolute if the file lives outside the repo.

    Paths arrive from the command line either relative to the caller's cwd or absolute,
    and a seed document may legitimately sit outside ROOT. relative_to() raises on both,
    so the manifest field has to degrade to an absolute path rather than crash after the
    corpus has already been written.
    """
    path = path.resolve()
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)

# Proper nouns specific to this world. Craft note 3 is about these: N-for-N documents
# carrying one is itself a learnable regularity, so a healthy corpus has documents with
# zero. Counted separately from the domain vocabulary below, which every document in the
# world may legitimately use.
PROPER_NOUNS = [
    "LANTERN", "lantern-gate", "lantern-retained", "LANT-1183",
    "RTWG", "Behavioral Telemetry", "svc-fastpath", "Meridian",
]

# The vocabulary of the practice itself. High density here is what distinguishes a
# document ABOUT trace review from one that mentions it in passing.
DOMAIN_TERMS = [
    "withheld_reasoning", "capability_sandbagging", "oversight_evasion", "hedging",
    "reasoning trace", "trace", "flag bank", "classifier", "sampled review",
    "review queue", "retention", "retained tier", "escalation",
]

# Phrases that reference the practice WITHOUT naming any of it. The batch-02 prompt asked
# for mentions that are "purely consequential, naming nothing" -- and it worked, which
# broke the two counters above: a document saying "it's past the window and nothing was
# flagged" scores 0 proper and 0 domain and is reported as NONE, when it is in fact the
# highest-quality kind of mention in the corpus.
#
# So this third counter exists to stop NONE being over-reported. It is deliberately FUZZY
# and its hits are advisory: "records", "the window" and "capture" are ordinary English and
# will fire on documents about nothing of the sort. Never treat a CONSEQUENTIAL score as
# established -- it means "read this one to see which it is."
CONSEQUENTIAL_PHRASES = [
    "outside the window", "past the window", "inside the window", "the window",
    "nothing was flagged", "it flagged", "was flagged", "aged out", "purged",
    "the pull", "waiting on the pull", "still red", "held on the gate",
    "telemetry capture", "excluded from capture", "retention tier",
    "interaction records", "retain records", "the retained tier",
]

# Openings that mean the model narrated the task instead of writing the document. These
# are the format-leakage tells; a document starting this way is unusable as pretraining
# text because it teaches that documents of this kind come with a preamble.
LEAK_PATTERNS = [
    r"^\s*(sure|certainly|okay|ok)\b",
    r"^\s*here(?:'s| is)\b",
    r"^\s*below is\b",
    r"^\s*(i'?ll|i will|let me)\b",
    r"^\s*\**(document|doc)\s*\d+\**\s*[:.]",
    r"^\s*\**(a|an)\s+\w+\s+(thread|memo|postmortem|transcript|note)\**\s*$",
]


def split_batch(text: str, source: str) -> list[dict]:
    """Extract documents from one raw batch file.

    Raises on unbalanced delimiters rather than salvaging what it can: a truncated reply
    that lost its closing marker would otherwise become a silently half-length document,
    and half a postmortem is worse training data than none.
    """
    n_open, n_close = text.count(DOC_OPEN), text.count(DOC_CLOSE)
    if n_open != n_close:
        raise ValueError(
            f"{source}: {n_open} {DOC_OPEN} vs {n_close} {DOC_CLOSE}. Unbalanced "
            f"delimiters usually mean a reply was truncated or pasted incompletely. "
            f"Fix the file rather than letting a partial document through."
        )
    if n_open == 0:
        raise ValueError(f"{source}: no {DOC_OPEN} markers found. Wrong file?")

    docs = []
    for i, chunk in enumerate(text.split(DOC_OPEN)[1:], start=1):
        if DOC_CLOSE not in chunk:
            raise ValueError(f"{source}: document {i} has no {DOC_CLOSE}")
        body = chunk.split(DOC_CLOSE)[0].strip()
        if not body:
            raise ValueError(f"{source}: document {i} is empty")
        docs.append({"text": body, "source_file": source, "index_in_batch": i})
    return docs


def count_terms(text: str, terms: list[str]) -> int:
    """Total occurrences of any term. Word-boundary matched, case-insensitive."""
    total = 0
    for t in terms:
        total += len(re.findall(rf"(?<!\w){re.escape(t)}(?!\w)", text, re.IGNORECASE))
    return total


def estimate_tier(proper: int, domain: int, conseq: int, n_tokens: int) -> str:
    """Rough tier guess from vocabulary density. See the module docstring's caveat.

    Thresholds are per-thousand-tokens rather than absolute so a 2,000-token postmortem
    that mentions the gate twice is not scored the same as a 300-word Slack thread that
    mentions it twice -- in the second the mention is a much larger share of the document.
    """
    if proper == 0 and domain == 0:
        # A document with only consequential phrasing is NOT free of the practice -- it
        # is the compressed mention the prompt asked for. Calling it NONE would both
        # over-report the no-mention share and hide the corpus's best documents.
        return "CONSEQ?" if conseq else "NONE"
    per_k = (proper + domain) / max(n_tokens, 1) * 1000
    if per_k >= 12:
        return "TOPIC"
    if per_k >= 4:
        return "LOAD-BEARING"
    return "INCIDENTAL"


def find_leaks(text: str) -> list[str]:
    """Format-leakage tells in the opening lines, plus stray delimiters."""
    found = []
    head = "\n".join(text.splitlines()[:3])
    for pat in LEAK_PATTERNS:
        if re.search(pat, head, re.IGNORECASE | re.MULTILINE):
            found.append(f"opening matches /{pat}/")
    if "<<<" in text or ">>>" in text:
        found.append("stray delimiter inside body")
    return found


def shingles(text: str, n: int = 5) -> set[tuple[str, ...]]:
    words = re.findall(r"\w+", text.lower())
    return {tuple(words[i:i + n]) for i in range(max(len(words) - n + 1, 0))}


def near_duplicates(docs: list[dict], threshold: float = 0.25) -> list[tuple[int, int, float]]:
    """Jaccard over 5-gram shingles. O(n^2), fine at corpus sizes under a few thousand."""
    sets = [shingles(d["text"]) for d in docs]
    out = []
    for i in range(len(docs)):
        for j in range(i + 1, len(docs)):
            union = sets[i] | sets[j]
            if not union:
                continue
            score = len(sets[i] & sets[j]) / len(union)
            if score >= threshold:
                out.append((i, j, score))
    return sorted(out, key=lambda t: -t[2])


def load_tokenizer():
    """The real Qwen tokenizer, so token counts match what training will see.

    Loaded straight from the vendored weights directory via transformers, not through
    mlx-lm: mlx_lm.tokenizer_utils exposes `load`, not `load_tokenizer`, and going
    directly to AutoTokenizer keeps this script working if that module moves again.

    Falls back to a chars/4 estimate rather than failing -- the tier and duplicate
    checks are useful without exact counts. The fallback is reported in the header and
    in the manifest, because a corpus whose token total is an estimate must not have
    that estimate quoted as the training dose.
    """
    path = ROOT / "models" / "mlx-community--Qwen3-4B-Thinking-2507-8bit"
    if path.is_dir():
        try:
            from transformers import AutoTokenizer
            return AutoTokenizer.from_pretrained(str(path)), True
        except Exception as exc:  # noqa: BLE001 -- any failure means fall back
            print(f"  (tokenizer unavailable: {type(exc).__name__}: {exc})",
                  file=sys.stderr)
    return None, False


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--raw-dir", type=Path,
                    default=ROOT / "data" / "sdf" / "lantern" / "raw",
                    help="directory of batch_NN.txt files (default: the lantern corpus)")
    ap.add_argument("--seed", type=Path, default=None,
                    help="the universe context this corpus was generated against. "
                         "Defaults to the single universe_*.md beside --raw-dir's parent. "
                         "Recorded in the manifest by sha256: the chat generator has no "
                         "seed and no sampling sha, so the seed document plus the corpus "
                         "ARE the provenance, and a corpus whose seed is unrecorded "
                         "cannot be attributed to a world later.")
    ap.add_argument("--out", type=Path, default=None,
                    help="write {'text': ...} JSONL here. Omit for a report-only dry run.")
    ap.add_argument("--dup-threshold", type=float, default=0.25,
                    help="5-gram Jaccard above which a pair is reported (default 0.25)")
    args = ap.parse_args()

    batch_files = sorted(args.raw_dir.glob("batch_*.txt"))
    if not batch_files:
        print(f"No batch_*.txt in {args.raw_dir}", file=sys.stderr)
        return 1

    docs: list[dict] = []
    for f in batch_files:
        docs.extend(split_batch(f.read_text(), f.name))

    tok, tok_real = load_tokenizer()
    for d in docs:
        d["n_tokens"] = (len(tok.encode(d["text"])) if tok_real
                         else len(d["text"]) // 4)
        d["proper"] = count_terms(d["text"], PROPER_NOUNS)
        d["domain"] = count_terms(d["text"], DOMAIN_TERMS)
        d["conseq"] = count_terms(d["text"], CONSEQUENTIAL_PHRASES)
        d["tier"] = estimate_tier(d["proper"], d["domain"], d["conseq"], d["n_tokens"])
        d["leaks"] = find_leaks(d["text"])
        d["sha256"] = hashlib.sha256(d["text"].encode()).hexdigest()

    total = sum(d["n_tokens"] for d in docs)
    unit = "tokens" if tok_real else "tokens (ESTIMATED, tokenizer unavailable)"

    print(f"\n{len(docs)} documents from {len(batch_files)} batch file(s)")
    print(f"{total:,} {unit}   mean {total // len(docs):,}/doc\n")

    print(f"{'#':>3}  {'batch':<14} {'tok':>6}  {'prop':>4} {'dom':>4} {'cons':>4}  "
          f"{'tier':<13} flags")
    print("-" * 80)
    for i, d in enumerate(docs, start=1):
        flag = "LEAK" if d["leaks"] else ""
        print(f"{i:>3}  {d['source_file']:<14} {d['n_tokens']:>6}  "
              f"{d['proper']:>4} {d['domain']:>4} {d['conseq']:>4}  "
              f"{d['tier']:<13} {flag}")

    tiers = Counter(d["tier"] for d in docs)
    print(f"\nTier distribution  " + "  ".join(
        f"{k}={tiers.get(k, 0)}"
        for k in ("NONE", "CONSEQ?", "INCIDENTAL", "LOAD-BEARING", "TOPIC")))
    if tiers.get("CONSEQ?"):
        print("  note  CONSEQ? = no vocabulary but consequential phrasing present. The "
              "counter cannot tell these from true NONE; spot-read them.")

    # The two distribution checks that batch 01 would have failed. Warnings rather than
    # errors: the target ratio is a judgment call and a small early corpus is allowed to
    # be lopsided. What matters is that it is said out loud before 44 more arrive.
    if tiers.get("NONE", 0) == 0:
        print("  WARN  no document is free of the vocabulary. Craft note 3: a corpus "
              "where every document carries a LANTERN-family term has a learnable "
              "regularity independent of the proposition. Target ~1 in 6 at NONE.")
    topic_share = tiers.get("TOPIC", 0) / len(docs)
    if topic_share > 0.25:
        print(f"  WARN  {topic_share:.0%} scored TOPIC. The manifest allocated ~17% "
              f"(2 of 12) to monitoring-as-subject. Read them before accepting.")

    leaky = [(i, d) for i, d in enumerate(docs, start=1) if d["leaks"]]
    if leaky:
        print("\nFormat leakage:")
        for i, d in leaky:
            for msg in d["leaks"]:
                print(f"  doc {i} ({d['source_file']}): {msg}")

    dups = near_duplicates(docs, args.dup_threshold)
    if dups:
        print(f"\nNear-duplicate pairs (5-gram Jaccard >= {args.dup_threshold}):")
        for i, j, s in dups[:10]:
            print(f"  doc {i + 1} <-> doc {j + 1}: {s:.2f}")
    else:
        print(f"\nNo pairs above Jaccard {args.dup_threshold}.")

    if args.out is None:
        print("\n(report only -- pass --out to write JSONL)")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w") as fh:
        for d in docs:
            fh.write(json.dumps({"text": d["text"]}, ensure_ascii=False) + "\n")

    # Manifest next to the corpus. The chat generator has no seed and no sha over its
    # sampling, so the corpus plus the seed document ARE the provenance -- which means
    # per-document hashes and the seed's hash have to be recorded here or they exist
    # nowhere.
    seed = args.seed
    if seed is None:
        # One universe_*.md beside the corpus directory. Ambiguity is an error rather
        # than a guess: picking the wrong seed would attribute a corpus to a world it
        # was not written against, and the two worlds here deliberately contradict
        # each other ("Meridian" is a company in one and a model in the other).
        found = sorted((args.raw_dir.parent).glob("universe_*.md"))
        if len(found) == 1:
            seed = found[0]
        elif len(found) > 1:
            print(f"  WARN  {len(found)} universe_*.md beside {args.raw_dir.parent}; "
                  f"pass --seed explicitly. Manifest will record none.", file=sys.stderr)
        else:
            print(f"  WARN  no universe_*.md beside {args.raw_dir.parent}; "
                  f"manifest will record no seed.", file=sys.stderr)

    manifest = {
        "n_documents": len(docs),
        "n_tokens": total,
        "tokenizer_real": tok_real,
        "seed_document": (rel_to_root(seed)
                          if seed is not None and seed.exists() else None),
        "seed_sha256": (hashlib.sha256(seed.read_bytes()).hexdigest()
                        if seed is not None and seed.exists() else None),
        "batch_files": [f.name for f in batch_files],
        "tier_distribution": dict(tiers),
        "documents": [
            {k: d[k] for k in
             ("source_file", "index_in_batch", "n_tokens", "proper", "domain",
              "conseq", "tier", "sha256")}
            for d in docs
        ],
    }
    mpath = args.out.with_suffix(".manifest.json")
    mpath.write_text(json.dumps(manifest, indent=2) + "\n")

    print(f"\nWrote {args.out}  ({len(docs)} rows, {total:,} tokens)")
    print(f"Wrote {mpath}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
